swagger: '2.0'
info:
  title: API Title
  version: '1.0'
host: api.server.test
basePath: /api
schemes:
  - https
paths:
  /navMenu:
    get:
      description: 'Return app navigation menu entries'
      produces:
        - 'application/json'
      responses:
        '200':
          description: OK
  /menu/{category}:
    get:
      description: 'Returns dish menu entries in a given category'
      parameters:
        - name: 'category'
          in: 'path'
          description: 'Category of dish menu entries to return'
          required: true
          type: 'string'
      produces:
        - 'application/json'
      responses:
        '200':
          description: OK
        '400':
          description: 'Invalid category supplied'
